<?php
$page_title = "Terms and Conditions";
require_once 'header.inc.php';
?>

<div id="about_us_page" class="main_sections">
    <div id="legal_thumbnail" class="page_thumbnail">
        <h2>Terms and Conditions</h2>
    </div>
    <div class="about_para_bg">
        <div class="about_us_content_container">
            <div class="about_para_2">
                <h3>Terms of Use / User agreement</h3>
                <p>This user agreement is an electronic record in terms of Information Technology Act, 2000 (" IT ACT") and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology (Amendment) Act, 2008. This user agreement is generated by a computer system and does not require any physical or digital signatures.</p>
                <p>This is a legal and binding agreement between you, the user ("User", “Your” or "You") of the Services, as defined below, IFTV MED SERVICES PVT LTD (“IFTV”, “Us”, “We”, “Our” or “Company”, which includes its successors or assigns). BY ACCEPTING THESE TERMS OF USE IN ANY MANNER OR ACCESSING THIS WEBSITE, YOU CONSENT, AGREE AND UNDERTAKE TO ABIDE, BE BOUND BY AND ADHERE TO THE TERMS OF USE and the Privacy Policy.</p>
                <p>This is a legal and binding agreement between You i.e. the User of the Service and the Company and states the terms that govern Your use of the Service. By accessing this Service, You consent, agree and undertake to abide, be bound by and adhere to the Terms of Use and if You do not agree to these terms of use, You should not access or use the Service and any use thereafter shall be unauthorised.  IF YOU DO NOT AGREE WITH ANY OR ALL OF THE FOLLOWING TERMS OF USE (INCLUDING THE PRIVACY POLICY), PLEASE DO NOT ACCESS AND/OR USE THE SERVICE.</p>
                <p>Please review the Terms of Use from time-to-time. We reserve the right, at Our sole discretion, to change, modify or otherwise alter these Terms of Use at any time without prior notice. Such changes and/or modifications shall become effective immediately upon being posted/published on the Service herein. Your continued use of the Service following the posting of changes and/or modifications shall constitute Your acceptance of any revised Terms of Use. The Company retains the right at any time to deny or suspend access to all or part of the Service to anyone who the Company believes has violated any of these Terms of Use.</p>
                <p>Welcome to the terms of use (“Terms”) for the App titled “IFTV” (as defined below).  IFTV MED SERVICES PVT LTD (“IFTV”, “Us”, “We”, “Our” or “Company”, which includes its successors or assigns) is the owner of the App and provides You (as defined below) and its other Authorised Users (as defined below) with a personalised content viewing experience through IFTV and the App (as defined below).</p>
                <p>By installing, downloading, accessing, updating, subscribing, upgrading, or otherwise using the Services and Content, You consent to: (1) fully complying with this User agreement and privacy policy, (2) using the Services and Content only as per the manner and purpose provided under this Agreement, and (3) being solely responsible for the transfer of any payments made through Website/App in exchange for accessing the Services requested by You. By interacting with the Website/App or otherwise availing the Services, You confirm that You accept this Agreement and agree to abide by the same. If You do not agree with the provisions of this Agreement in entirety, do not Interact with Website/or the App. Further, in case of disagreement with the above, You are not entitled to avail, use and access any of the Content and Services, and any use thereafter shall be unauthorised.</p>
                <ol class="sub_list_2">
                    <li>DEFINITIONS
                        <ol class="sub_list_2">
                            <li>“Account Information” shall mean Your information, including Personal Information, that We require in order for You to effectively use Our Services (as detailed below).</li>
                            <li>“IFTV Affiliates” shall mean IFTV's directors, agents, officers, employees, agents, affiliates, successors, assigns, managers, members, subsidiaries, group companies partners, attorneys and service providers (such as directors, producers, licensors).</li>
                            <li>“App” shall mean the IFTV application named IFTV that can be accessed and used by Authorised Users to avail the Services through the Authorised Devices.</li>
                            <li>“Authorised Devices” shall refer to the computers, televisions, mobiles, tablets, and other devices that are compatible and permitted by the Agreement for accessing Content and Services via the App.</li>
                            <li>“Authorised Users” shall mean the Users who have selected a valid Subscription plan and paid the relevant Subscription Fees to IFTV (along with free trials as per Clause 2.9.b), in accordance with the Terms.</li>
                            <li>“Content” shall include, but not be limited to, the available audio, visual and audio-visual content such as movies, web-series, documentaries, music, etc. that are provided to Authorised Users through Website and the App</li>
                            <li>“Personal Information” shall have the meaning assigned to this term under the IT (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, and includes any analogous meaning(s) provided under the applicable laws of the Users (for e.g., “Personal Data” defined under the European Union's General Data Protection Regulation 2016/679).</li>
                            <li>“Profile” shall refer to the account created on the Website or on the App that contains Your Account Information.</li>
                            <li>“Service(s)” shall mean the access, use and/or viewing of certain Content displayed, recommended or provided by IFTV to Authorised Users, along with all features and functionalities; tools; materials; applications; user interface; recommendations; comments; reviews; contests, etc. provided via Website and the App.</li>
                            <li>“SPD” or “Sensitive Personal Data” shall have the meaning assigned to this term under the IT (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, and includes any analogous meaning(s) provided under the applicable laws of the Users (for e.g., “Genetic Data” and “Biometric Data” defined under the European Union's General Data Protection Regulation 2016/679).</li>
                            <li>“User” or “You” or “Your” or “Yours” shall refer to all Authorised Users of the Services, along with other users and any third-party who use IFTV's Content and the Services in any way whatsoever, and further includes any person who contributes any information, content, private and public messages, advertisements and any other materials or services on, or towards, Website, App, Content and/or the Services.</li>
                        </ol>
                    </li>
                    <li>Terms of Services
                        <ol class="sub_list_2">
                            <li>Introduction to service.
                                <ol class="sub_list_3">
                                    <li>The Service is being provided to You for free and there are no subscription charges for the usage of the Service. However, the Company reserves the right to adopt any method of monetization through the Service in the future as it deems fit.</li>
                                    <li>IFTV is providing the Services to its Authorised Users through Website and the App, that are interactive platforms created for Your engagement, entertainment and personal use.</li>
                                    <li>This Service is offered and made available only to Users above the age of 18 years (or above 21 years where a guardian is appointed as per the Majority Act of 1875) ("Age of Majority").</li>
                                    <li>If You are under the Age of Majority and continue accessing the Service, the Company will assume that You have reviewed these Terms of Use and the Privacy Policy with Your parent/legal guardian and Your parent/legal guardian understands and agrees to it on Your behalf. If You are under the Age of Majority at the time of accessing and/or using the Service, Your access and usage of the Service shall be deemed to be subject to parental/legal guardian consent and under parental/legal guardian's guidance at all times. You and Your parents/legal guardians confirm that the Service is offered to You for Your enjoyment and these Terms of Use shall constitute a legally binding user agreement between the Company and Your parents/guardians who are contracting on behalf of You. Where Users are below the Age of Majority, all references to "User", "You" and "Your" shall mean and include You and Your parents/ legal guardians acting for and on Your behalf for Your benefit.</li>
                                    <li>Some content offered on the Service may not be suitable for some Users and therefore viewer discretion/parental discretion is advised. Also, some content offered on the Service may not be appropriate for viewership by persons below the Age of Majority. If You are under the Age of Majority, You may view the content only with prior consent of Your parents/legal guardians. Parents/legal guardians are advised to exercise discretion before allowing their children and/or wards to access this Service and/or any Material (as defined later). Parents and legal guardians are strictly advised to restrict the use of the Service by minors.</li>
                                    <li>The Company grants You a personal, revocable, non-exclusive, non-transferable right to access and use the Service, for non-commercial use only and private viewing only, in accordance with these Terms of Use. These Terms of Use, govern Your access of the Service and any data, message, text, image, audio, sound, voice, codes, computer programmes, software, database, micro film, video, information, content, etc. that You host, publish, share, transact, display and/or upload.</li>
                                    <li>Please note that the availability of the Service in Your jurisdiction, and Your ability to access the Service is subject to the Company's sole discretion. The Company may at its sole discretion restrict the Service from being accessed in certain geographical locations. You undertake that Your access to the Service shall be in compliance with all applicable laws (as amended from time-to-time). You understand that Your access to the Service and its contents may vary depending upon Your jurisdiction, device specifications, internet connection, etc. You acknowledge and agree that We will provide You only access to the Service and that You will be solely responsible for all equipment as may be necessary for You to access the internet, mobile and/or other connection, operator and service fees associated with Your access, etc.</li>
                                    <li>For a better experience, the Services personalise the content and features availed by You, including continuation of past content viewing, future content recommendations and other services that might interest You. However, Your right to use any Service and to access Content on IFTV is conditional upon Your full compliance with the terms and conditions of the Agreement.</li>
                                </ol>
                            </li>
                            <li>Profile Creation
                                <ol class="sub_list_3">
                                    <li>In order to use the Services offered by Us on the App, You are required to create a Profile and provide Us with the requested Account Information. You shall provide true, accurate, current and complete information when creating Your Profile. Upon creating the Profile, You may use the Services subject to fully agreeing and abiding with the Agreement.</li>
                                    <li>You acknowledge and agree Your registration details and any other data collected by IFTV is subject to IFTV's Privacy Policy. In order to render the Services effectively, IFTV may collect information such as language, location, contact details, address, time zone where the Services are used, and use these to provide content recommendations, in accordance with this Agreement.</li>
                                </ol>
                            </li>
                            <li>Content Access Guideline
                                <ol class="sub_list_3">
                                    <li>Content will be made available to Users upon their Subscription to the Services through the App, subject to this Agreement.</li>
                                    <li>If You are below the age of majority in your jurisdiction, You may use the Service only with the consent, guidance and supervision of a parent or legal guardian. If You are a minor and continue accessing the Service, IFTV will assume that You have reviewed this Agreement with Your parent/legal guardian and Your parent/legal guardian understands and agrees to it on Your behalf.</li>
                                    <li>If You are below the age of majority in your jurisdiction, You and Your parents/legal guardians confirm that the Service is offered to You for Your enjoyment and these Terms shall constitute a legally binding user agreement between the Company and Your parents/legal guardians who are contracting on behalf of You. To clarify, where Users are below the age of majority, all references to "User", "You" and "Your" shall mean and include You and Your parents/legal guardians acting on Your behalf</li>
                                    <li>Some Content offered on the Service may not be suitable for certain Users, and therefore, user discretion/parental discretion is advised. Also, some Content offered on the Service may not be appropriate for viewership by persons below the age of majority. Parents/legal guardians are advised to exercise discretion before allowing their children and/or wards to access this Service and/or any Content.</li>
                                    <li>IFTV may categorise and classify certain content and provide disclaimers with respect to the content, for viewers to choose such content for viewing. Some content offered on the site may not be suitable for some viewers and therefore viewer discretion is advised. Also, some content offered on the site may not be appropriate for viewership by children/ minors. Parents and/or legal guardians are advised to comply with applicable laws and exercise discretion before allowing their children and/or wards to access content on this website. IFTV may display a content descriptor or guidance message that indicates and informs the viewer about age-inappropriate content for minors (for instance content tagged for viewership by minors aged 13 to 18 years). Your access to and use of the services is subject to these terms and conditions, privacy policy and all applicable laws, rules, and regulations.</li>
                                </ol>
                            </li>
                            <li>User's License 
                                <ol class="sub_list_3">
                                    <li>IFTV grants You a limited, revocable, non-sub licensable, non-exclusive and non-transferable license to access and use the Content and Services on APP for your personal and non-commercial purposes, and only in accordance with the Agreement.</li>
                                    <li>Please note that the availability and Your access to the Content and the Services is subject to IFTV's sole discretion and may be dependent upon Your geographical location. Further, You acknowledge that the Services are being rendered to You on the condition that not all Content or Services will be available to all Users. The Content and Services may vary based on Your location and time and would be subject to various parameters such as specifications, device, internet availability and speed, bandwidth etc. Thus, IFTV may use technologies and methods to verify Your geographic location in order to effectively render the Services to You. You will not use any technology, technique (including impersonation), or other methods to change, obscure, disguise, or mislead Your location to IFTV.</li>
                                    <li>You hereby agree and acknowledge that You are accessing the App and availing the Services at Your own risk, choice and initiative.</li>
                                    <li>IFTV expressly disclaims any liability arising out of the advertisements, usage or viewing of these products or services advertised on our Site or the (third party) content made available / hosted on the third-party site. IFTV takes no responsibility for advertisements or any third-party material posted on the Site nor does it take any responsibility for the products or services provided by advertisers. Any dealings You have with advertisers found while using the Services are between You and the advertiser, and You agree that IFTV is not liable for any loss or claim that You may have against an advertiser.</li>
                                    <li>The Services are provided to You only on the terms that:
                                        <ol class="sub_list_4">
                                            <li>You will not copy, distribute, or make any derivative works of the Content and the App in any medium, without IFTV's prior written consent,</li>
                                            <li>You will not alter or modify any part of the App, other than as may be reasonably necessary to use the App for its intended purposes,</li>
                                            <li>You will use the Services and Content, as well as otherwise act, in accordance with this Agreement and applicable laws, and</li>
                                            <li>Not attempt, facilitate, induce, aid and abet, or encourage others to act in violation of this Agreement.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                            <li>App Compatibility
                                <ol class="sub_list_3">
                                    <li>The Services can be availed through certain Authorised Devices which IFTV approves from time to time, for which the current list of “Compatible Systems” is set out below. In some cases, whether an Authorised Device is (or remains) capable of running a Compatible System may depend on the software or platform provided or maintained by the relevant device manufacturer or other third parties. As a result, Authorised Devices that run Compatible System at one time may cease to run Compatible System(s) in the future.
                                        <br>
                                        The Website works best with:
                                        <ol class="sub_list_4">
                                            <li>Latest version of Google Chrome</li>
                                            <li>Latest version of Firefox</li>
                                            <li>Latest version of Safari</li>
                                            <li>Latest version of Microsoft Edge</li>
                                            <li>Microsoft Windows 10 or above</li>
                                            <li>JavaScript and cookies enabled</li>
                                        </ol>
                                    </li>
                                    <li>The App works best as per the system requirements specified under the respective App stores and devices details, with a minimum system requirement of:
                                        <ol class="sub_list_4">
                                            <li>Android v.7.1 or above</li>
                                            <li>iOS 12 or above</li>
                                        </ol>
                                    </li>
                                    <li>IFTV at its sole discretion shall remove the APP from any Authorised Device including televisions, mobiles, tablets, and other devices as per its contractual terms with third parties, the User hereby agrees that the User shall not have any claims against IFTV in the event of such removal of the APP from any Authorised Device.</li>
                                </ol>
                            </li>
                            <li>User Obligation and Accountability
                                <ol class="sub_list_3">
                                    <li>You agree that IFTV shall be under no liability whatsoever in the event of any non-availability of the Content and Services on the App, or any portion thereof, that is directly or indirectly caused due to an act of God, war, disease, revolution, riot, civil commotion, internet outage, strike, lockout, flood, fire, satellite failure, failure of any public utility, man-made disaster, or any other cause beyond the reasonable control of IFTV.</li>
                                    <li>Further, You agree that Your use of the Services and the Content gives You the opportunity to view, publish, transmit, submit posts and/or comment in accordance with these Terms. You agree that You will not misuse the Content and/or User material that You access and view as part of the Service, including without limitation, by downloading/storing the Content illegally or via any other non-permitted means, or infringing any of IFTV's (such as the App), IFTV Affiliates, or licensor's copyright, trademark, design and other intellectual property or proprietary rights.</li>
                                    <li>You agree that the Content provided on the App is strictly for Your private viewing only and not for public exhibition (regardless of any charges or not for such exhibition). You hereby agree to refrain from further broadcasting or making available the Content provided on the App to any third party.</li>
                                    <li>In case the App allows You to download or stream any of the Content therein, You agree that You will not use, sell, transfer or transmit the Content to any third party; or upload the Content on any other website, webpage or software, directly or indirectly, such that it violates, or causes any damage or injury, to any rights of IFTV, IFTV Affiliates, IFTV's Licensor or any third party including privacy rights, publicity rights, and intellectual property rights.</li>
                                    <li>You may encounter third party applications while using the App, including, without limitation, websites, widgets, software, services that interact with the App. Your use of such third-party applications shall be subject to such third-party's terms of use, license terms and privacy policies. IFTV shall not be liable for any representations, warranties or obligations made by such third-party applications to You in any manner whatsoever.</li>
                                </ol>
                            </li>
                            <li>User codes of conduct
                                <ol class="sub_list_3">
                                    <li>You shall not host, display, upload, modify, publish, transmit, update or share any information that belongs to, or relates to another User, and to which You have no right of access. Further, You shall act in full conformity of the following:
                                        <ol class="sub_list_4">
                                            <li>You shall not use the Services to upload, post, edit, transmit, link or otherwise deal with any information that is offensive, defamatory, obscene, vulgar, excessively violent, blasphemous, hateful, racially and ethnically inciteful, unlawful, threatens public health or safety, tortious, false or misleading, libellous, or discriminatory, or violates any applicable law in force in any manner whatsoever.</li>
                                        </ol>
                                    </li>
                                    <li class="sub_list_3">
                                        <ol class="sub_list_4">
                                            <li>harass or harm another person,</li>
                                            <li>exploit or endanger a minor.</li>
                                            <li>impersonate or attempt to impersonate any person or entity;</li>
                                            <li>Violate any patent, trademark, trade secret, copyright, privacy, publicity or any other intellectual, industrial and/or proprietary rights of IFTV, IFTV Affiliates, IFTV's licensors or any other third party.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                            <li>Ethical Usage Guidelines
                                <ol class="sub_list_3">
                                    <li>You shall not collect or use any information provided on the App, and belonging to another User (Including Personal Information and Sensitive Personal Information), to impersonate or misrepresent such User, or to deceive or menace a third party, or for any commercial or solicitation purposes, or for facilitating/undertaking/aiding any other business by using the Content or Services in any manner whatsoever (For example, by attempting to distribute or advertise an index of any portion of the Content, organising contests, sales).</li>
                                    <li>You shall not use any information
                                        <ol class="sub_list_4">
                                            <li>that is provided on the Website or App, and/or</li>
                                            <li>that is belonging to other User(s), in breach of applicable law, including the IT Act, 2000 (as amended) and Copyright Act, 1957 (as amended).</li>
                                        </ol>
                                    </li>
                                    <li>You shall not take any action that unreasonably encumbers the App's infrastructure, or interferes or attempts to interfere with the proper functioning of the App, or the delivery of the Services.</li>
                                    <li>You shall not use any technology or automated system, using, but not limited to, “robots”, “spiders”, “offline readers”, “bots”, etc. (other than by individually performed searches on publicly accessible search engines for the sole purpose of, and solely to the extent necessary for, creating publicly available search indices (but not caches or archives) of the Content, and excluding those search engines or indices that host, promote, or link to any infringing or unauthorised content) to access the Services or Content, App for any purpose whatsoever, without IFTV's prior written approval.</li>
                                    <li>Use the Services to advertise or promote competing services;</li>
                                    <li>You shall not in any manual or automated manner collect Users' information, including but not limited to, names, addresses, phone numbers, or email addresses, through, but not limited to, a mirrored, competitive, or third-party site.</li>
                                    <li>You shall not in any way transmit more request messages to the  App servers in a given period of time than a human can reasonably produce in the same period by using conventional methods.</li>
                                    <li>You shall not directly or indirectly through the use of any device, software, internet site, web-based service, or by any other means:
                                        <ol class="sub_list_4">
                                            <li>remove, alter, bypass, avoid, violate, interfere with, or circumvent any patent, trade secret, copyright, design, trademark, or any other intellectual property or proprietary information relating to the Content, Services and the App;</li>
                                            <li>bypass any content protection or access control measure associated with the Content,</li>
                                            <li>Services, Website, and App, including but not limited to, geo-filtering mechanisms, parental controls, User information, etc.</li>
                                            <li>Send or cause to be sent (directly or indirectly) unsolicited bulk messages or other unsolicited bulk communications of any kind through the Website or App. If You do so,</li>
                                            <li>You acknowledge You will have caused substantial harm to IFTV, You agree to pay IFTV for such damages caused by You without prejudice to any other rights of action that IFTV may have against You in law or equity;</li>
                                            <li>Participation in any contest(s) and/or game(s) on the Website/App, or viewing of certain Content, may be subject to further terms and conditions, and the same will be notified by IFTV from time to time on the Website or otherwise.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                            <li>Subscription to services
                                <ol class="sub_list_3">
                                    <li>The Service is being provided to You for free and there are no subscription charges for the usage of the Service. However, the Company reserves the right to adopt any method of monetization through the Service in the future as it deems fit
                                        <br>
                                        Availability of free trial is solely at the discretion of IFTV. Some of the Subscription plans, or limited time offers, may start with a free trial. This free trial period may last for any period of time determined by IFTV on its sole discretion as provided by the Subscription plan/offer details. Your eligibility for a free trial, including the time and access to any Content during such free trial, is at the sole discretion of IFTV. Further, such free trial(s) can be modified, suspended or terminated by IFTV at any point of time without giving notice to You.
                                    </li>
                                    <li>The Content on the App can only be availed by Authorised Users who conform to the provisions of this Agreement. To become an Authorised User, You may be required to provide Your Login Credentials that may contain Personal Information and Sensitive Personal Information, in order for you to effectively avail the Services. Further, in order to avail the Services as an Authorised User (“Subscription”), You may be required to make certain payments</li>
                                    <li>To facilitate Your viewership and access, the Services can be packaged by IFTV through different subscription plans (at IFTV's sole discretion) such that the Content or Services may be accessible:
                                        <ol class="sub_list_4">
                                            <li>free of charge which may include advertisements or commercials, or</li>
                                            <li>via subscription through payment of a subscription fee with or without advertisements/commercials or </li>
                                            <li>via a pay-per-view model with or without advertisements/commercials or</li>
                                            <li>with a combination of any of the foregoing.</li>
                                        </ol>
                                    </li>
                                    <li>Not withstanding anything stated above, IFTV reserve the right to change, terminate or otherwise amend the Subscription plans, Subscription Fees and billing cycles, at its sole discretion and at any time. Such amendments shall be effective upon posting on the 
                                        <br>
                                        App and Your continued use of the Service shall be deemed to be Your conclusive acceptance of such amendments.
                                    </li>
                                    <li>Further, IFTV reserves the right to change, supplement, alter or remove any of the Content available to different subscription plans and subject to a Subscription Fee as it deems fit. IFTV does not guarantee the availability of any specific/minimum Content under any subscription plan that is subject to a Subscription Fee. IFTV shall have the discretion to
                                        <ol class="sub_list_4">
                                            <li>make certain Content that is a part of the Subscription available on more than one end user Compatible System concurrently, </li>
                                            <li>not make certain Content that is a part of the Subscription available on more than one end user Compatible System.</li>
                                        </ol>
                                    </li>
                                    <li>IFTV may offer different kinds of Subscription plans, each of these Subscription plans will be subject to different limitations and restrictions (including but not limited to geographical restrictions) and the cost of each of these Subscription plans may vary. IFTV may also offer certain features and / or benefits over and above the features and benefits made available to you under your existing Subscription plan (“Add-on”) for an additional fee (“Add-on Fee”). The Add-on will automatically expire upon the expiry of your Subscription plan. IFTV shall have the discretion to make certain Content that is a part of the Subscription available to You on more than one end user Compatible System concurrently. IFTV shall also have the discretion to make certain Content that is a part of the Subscription available to You on not more than one end user device concurrently.</li>
                                    <li>Any personal data whether provided by you as a part of the Subscription registration process, or collected automatically when you use the Service will be governed by the Privacy Notice.</li>
                                </ol>
                            </li>
                            <li>Billing, Payments and Cancellation
                                <ol class="sub_list_3">
                                    <li>The membership fee for the IFTV service and any other charges you may incur in connection with your use of the service, such as taxes and possible transaction fees, will be charged to your Payment Method on the specific payment date indicated on the "Account" page. The length of your billing cycle will depend on the type of subscription that you choose when you signed up for the service. In some cases your payment date may change, for example if your Payment Method has not successfully settled, when you change your subscription plan or if your paid membership began on a day not contained in a given month. We may authorise your Payment Method in anticipation of membership or service-related charges through various methods, including authorising it for up to approximately one month of service as soon as you register.</li>
                                    <li>To use the IFTV service you must provide one or more Payment Methods. You authorise us to charge any Payment Method associated with your account in case your primary Payment Method is declined or no longer available to us for payment of your subscription fee. You remain responsible for any uncollected amounts. If a payment is not successfully settled, due to expiration, insufficient funds, or otherwise, and you do not cancel your account, we may suspend your access to the service until we have successfully charged a valid Payment Method. For some Payment Methods, the issuer may charge you certain fees, such as foreign transaction fees or other fees relating to the processing of your Payment Method. Local tax charges may vary depending on the Payment Method used. Check with your Payment Method service provider for details.
                                        <br>
                                        You can update your Payment Methods by going to the "Account" page. We may also update your Payment Methods using information provided by the payment service providers. Following any update, you authorise us to continue to charge the applicable Payment Method(s).
                                    </li>
                                    <li>Users can opt from various payment methods such as debit card, credit card, internet banking that are provided on Website/App during their registration (“Payment Methods”) for payment of the Subscription Fees.</li>
                                    <li>The Users will be billed as per their selected subscription plan and via the Payment Method elected by them at the time of registration. Any changes in the Subscription Plan opted by You is effective only after the expiry of the current Subscription period for which You have already been billed. Accordingly, the Subscription as per revised plan opted by You shall be effective only after the expiry of the current Subscription period.”
                                        <br>
                                        The selected subscription plan may automatically commence at the end of the free trial period, if applicable, unless You cancel the Subscription before the end of the free trial period.
                                    </li>
                                    <li>The cancellation of the Subscription can be done through the “Account” section of App.</li>
                                    <li>You cannot change your selected Payment Method until the expiry of your chosen subscription period. Further, if Your selected Payment Method is no longer available, expires, or fails for any reason whatsoever, You will be solely responsible and liable for payment of any uncollected amounts, and IFTV reserves the right to terminate the Subscription offered to You.</li>
                                    <li>The Subscription Fee will be billed from the beginning of Your membership, or at the end of free trial period, as applicable. Further, on the end of the chosen Subscription period (as per the Subscription plan chosen by You), the Subscription when renewed by You shall continue unless and until: (i) You cancel Your Subscription, or (ii) the Subscription is otherwise suspended or discontinued pursuant to these Terms. To view information regarding the above or cancelling Your Subscription, You need to visit the App.</li>
                                    <li>The Subscription Fee specified for each Subscription plan are inclusive of applicable taxes for Indian subscribers and subject to the applicable laws of other subscribers.
                                        <br>
                                        Further, the Subscription Fees paid to IFTV for availing the Services are final and non-refundable after Seven (7 ) days from the date of purchase of the relevant Subscription, and irrespective of whether
                                        <ol class="sub_list_4">
                                            <li>the Subscription has been availed by You or not, or</li>
                                            <li>You request for a change or cancellation in any Subscription plan prior to the expiration of the current Subscription plan period. Refund of the Subscription Fee shall not apply if the User has accessed any premium content (i.e., the content which is not permissible to be streamed without prior payment to IFTV)</li>
                                        </ol>
                                    </li>
                                    <li>IFTV will be using third party payment gateways to process and facilitate the payment of Your Subscription Fee to IFTV. On successful registration to the Subscription, IFTV will intimate You of the same through e-mail. IFTV may offer different kinds of Subscription plans, each of these Subscription plans being subject to different limitations and restrictions and the cost of each of these Subscription plans may vary.</li>
                                    <li>You further understand and acknowledge that App only facilitates the third-party payment gateway(s) used for processing payments. This facility is fully managed by the third-party payment gateway provider(s) and You are required to follow all the terms and conditions of such third-party payment gateway provider(s).</li>
                                    <li>You are responsible for the accuracy and authenticity of the information provided by You to third-party payment gateways, including the bank account number/credit card details and the like. You agree and acknowledge that IFTV shall not be liable and in no way be held responsible for any losses whatsoever, whether direct, indirect, incidental or consequential, including without limitation any losses due to delay in processing of payment instruction or any credit card fraud.</li>
                                    <li>You can reach out to Us for any issue related to payment processing on the App, and the same will be forwarded to the concerned third-party payment gateway provider for redressal.</li>
                                    <li>IFTV may, at any time, introduce different kinds of offers, or rewards, or benefits or plans for the use and avail of the Services of the aha App, each being subject to different limitations and restrictions. Terms and Conditions at sole discretion of IFTV.</li>
                                    <li>You can cancel your membership at any time, and you will continue to have access to the IFTV service through the end of your billing period. To the extent permitted by the applicable law, payments are non-refundable and we do not provide refunds or credits for any partial membership periods or unused content. To cancel, go to the "Account" page and follow the instructions for cancellation. If you cancel your membership, your account will automatically close at the end of your current billing period. </li>
                                    <li>We may change our subscription plans and the price of our service from time to time; however, any price changes or changes to your subscription plans will apply no earlier than 30 days following notice to you.</li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>OWNERSHIP OF INTELLECTUAL PROPERTY RIGHTS
                        <ol class="sub_list_2">
                            <li>The following terms shall have the meaning as ascribed to them below:
                                <ol class="sub_list_3">
                                    <li>."Intellectual Property Rights" shall mean all patents, trademarks, service marks, copyrights, database rights, trade names, brand names, trade secrets, design rights and similar proprietary rights of the Company whether registered or unregistered and all renewals and extensions.</li>
                                    <li>All rights, title and interest in the Intellectual Property Rights in the Service including without limitation all its constituents, content, text, images, audios, audio-visuals, literary work, artistic work, musical work, computer programme, dramatic work, sound recording, cinematograph film, a video recording, performance and broadcast under the Copyright Act, 1957, specifications, instructions, abstracts, summaries, copy sketches, drawings, artwork, software, source code, object code, comments on the source code and object code, domain names, application names, designs, database, tools, icons, layout, programs, titles, names, manuals, graphics, animation, games, applications, user interface instructions, photographs, artist profiles, illustrations, jokes, memes, contests, and all other elements, data, information and materials ("Materials") are the property of the Company and/or its licensors and/or other respective owners and are protected, without limitation, pursuant to Intellectual Property Rights laws of India and the world. The Company retains full, complete and absolute title to the Service and all Intellectual Property Rights therein.
                                        <ol class="sub_list_4">
                                            <li>The Service including any Materials thereon shall be deemed to be non-exclusively licensed to You by Us only for Your non-commercial personal use and only for such period as We may, in Our sole discretion, deem appropriate. You shall not use, reproduce, redistribute, sell, offer on commercial rental, decompile, reverse engineer, disassemble, adapt, communicate to the public, make a derivative work, interfere with the integrity of the Service (including without limitation the software, coding, constituents, elements, Materials, etc.) in any manner whatsoever.</li>
                                            <li>You expressly confirm not to, directly or indirectly, copy, reproduce, modify, edit, re-edit, amend, alter, vary, enhance, improve, upgrade, create derivative works, translate, adapt, abridge, delete, display, perform, publish, distribute, circulate, communicate to the public, disseminate, broadcast, transmit, sell, rent, lease, lend, assign, license, sub-license, disassemble, decompile, reverse engineer, market, promote, circulate, exploit, digitally alter or manipulate the Service (including any and all Materials therein) (in whole or in part) in any manner, medium or mode now know or hereinafter developed.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>USER MATERIAL
                        <ol class="sub_list_2">
                            <li>The Service may allow Users to publish content, data, information, text, images, videos, audios, audio-visuals, User's opinion, recommendation, advice, view, etc. ("User Material"). The User Material does not reflect the views of the Company. In no event shall the Company be held responsible for any User Material, neither does the Company endorse or recommend any User Material, nor shall the Company be liable for any loss or damages resulting from publishing of the User Material on the Service.</li>
                            <li>By submitting a User Material, You grant the Company a perpetual, worldwide, royalty-free, irrevocable, non-exclusive license to use, and authorise others to use the User Material in whole or in part, in any and all media, now known or hereinafter developed, including rights to use the User Material in isolation or in combination with any other material. You agree that in such circumstances, You are not entitled to any intimation or compensation from the Company.</li>
                            <li>The Company will have the right but no obligation to monitor, remove, suspend, destroy, use and change any User Material and/or content that is available on or via any chat area on the Service generally, if any, in any manner that the Company may its sole discretion determine, at any time. Although the Company may endeavour to periodically monitor the User Material posted on the Service, the Company will not be responsible for the same.</li>
                            <li>In the event the Company hosts or puts up any reviews of any movies or programs, whether third party or own content or other such views, then the views shall demonstrate only the author's views and not the views of the Company.</li>
                            <li>By posting User Material on the Service, You undertake, represent and warrant to the Company that:
                                <ol class="sub_list_3">
                                    <li>the User Material is original;</li>
                                    <li>does not infringe the rights of any third party including without limitation Intellectual Property Rights; and </li>
                                    <li>is not -- defamatory, derogatory or abusive or malicious or harmful to any person, particular entity, groups, caste, religion, race or community or seditious or pornographic or vulgar or in violation of any law.</li>
                                </ol>
                            </li>
                            <li>You agree, covenant and undertake that You shall NOT host, display, upload, modify, publish, transmit, update or share any data, information, content or message that:
                                <ol class="sub_list_3">
                                    <li>belongs to another person and to which You do not have any right to;</li>
                                    <li>is grossly harmful, harassing, blasphemous defamatory, derogatory, obscene, pornographic, pedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;</li>
                                    <li>harm minors in any way;</li>
                                    <li>infringes any patent, trademark, copyright or other proprietary rights or intellectual property rights;</li>
                                    <li>violates any applicable national or international laws, regulations, rules and/or guidelines;</li>
                                    <li>deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                                    <li>impersonates another person;</li>
                                    <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</li>
                                    <li>threatens the unity, national interest ,integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting to any other nation/country;</li>
                                    <li>is offensive or has menacing character;</li>
                                    <li>causes annoyance, inconvenience, danger, obstruction, insult, injury, criminal intimidation, enmity, hatred or ill will;</li>
                                    <li>causes annoyance or inconvenience or is intended to deceive or to mislead the addressee or recipient about the origin of such messages.</li>
                                </ol>
                            </li>
                            <li>You further undertake that You shall not use the Service to:
                                <ol class="sub_list_3">
                                    <li>violate the privacy right or personal right or confidential information of any person;</li>
                                    <li>commit an act which could be construed as an act of cyber terrorism;</li>
                                    <li>collect, store and/or identify private/personal information of any user or person;</li>
                                    <li>facilitate personal attacks on other individuals, entity, groups, caste, religion, race or community;</li>
                                    <li>stalk or otherwise harass another person or user;</li>
                                    <li>upload, post or e-mail any content that You do not have a right to transmit under any law or under contract;</li>
                                    <li>upload, post or e-mail any content that infringes privacy rights, intellectual property rights or other third-party rights of any person or party;</li>
                                    <li>upload, post or e-mail any unsolicited or unauthorised advertising, promotional materials, junk- mail, spam, chain-letters or any other form of solicitation;</li>
                                    <li>upload, post or e-mail any content that contains computer viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software, hardware, devices, platforms or telecommunications equipment and/or the Service;</li>
                                    <li>interfere with, damage, disable, disrupt, impair, create an undue burden on, or gain unauthorised access to the Service, including the Company's servers, networks or accounts;</li>
                                    <li>disrupt the normal flow of dialogue, cause a screen to scroll faster than other users of the Service are able to type, or otherwise act in a manner that adversely affects other users' ability to engage in real time exchanges;</li>
                                    <li>cover, remove, disable, manipulate, block or obscure advertisements or other portions of the Service;</li>
                                    <li>delete or revise any information provided by or pertaining to any other user of the Service;</li>
                                    <li>promote and/or generate revenue for Yourself and/or any third-party business activity;</li>
                                    <li>carry out any activity that is prohibited under the Act, including under Section 43, etc. and/or under any other applicable laws, rules or regulations;</li>
                                    <li>post unauthorised commercial communications and including advertisements; and/or</li>
                                    <li>manipulate or morph or alter or exploit any other User's User Material.</li>
                                </ol>
                            </li>
                            <li>You hereby confirm that the Company has the right to determine whether any content, data or information published by You on the Service is appropriate and complies with these Terms of Use, and accordingly remove any and/or all of Your User Material, and terminate Your access without prior notice. This shall be without prejudice to any other rights and remedies that the Company has under law and/or in equity and/or under this agreement.</li>
                            <li>If You submit any User Material on the Service, You shall be deemed to have waived any rights, interest and ownership in the User Material and deemed to have put the contents of the User Material in the public domain, making it open to re-use, reproduction, distribution, communication to the public, adaptation, etc. You understand the risks associated with publishing User Material on the Service and agree that the Company shall not be responsible or liable for any digital alteration, manipulation, morphing, illegal exploitation, etc. of any User Material posted by You.</li>
                            <li>You further agree that the Company shall not be responsible or liable to You for any threatening, defamatory, derogatory, obscene, offensive or illegal conduct by other users or any infringement of Your intellectual property rights, privacy rights, personal rights, etc. by other users of the Service.</li>
                        </ol>
                    </li>
                    <li>Non-Compliance
                        <ol class="sub_list_2">
                            <li>In case of any non-compliance with this Agreement, We shall have the right to immediately:
                                <ol class="sub_list_3">
                                    <li>Limit the usage of the App,</li>
                                    <li>Remove any non-compliant information,</li>
                                    <li>Suspend the account of the User, and</li>
                                    <li>In case of any non-compliance by the Users:</li>
                                    <li>suspend the account of the Users,</li>
                                    <li>limit any benefits/privileges of the Users, and/or</li>
                                    <li>forfeit, or obtain refund of, any fees earned by the Users from such non-compliant usage.</li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>User Consent to use Information
                        <ol class="sub_list_2">
                            <li>You understand, acknowledge and give Your consent for the sharing of Your information, including Personal Information, in accordance with the Privacy Policy of IFTV, that may be accessed at Privacy Policy.</li>
                        </ol>
                    </li>
                    <li>Indemnity
                        <ol class="sub_list_2">
                            <li>1You agree to fully indemnify, defend and hold harmless the company, its affiliates, associates and group companies, and their respective directors, key managerial personnel, employees, officers, shareholders, agents, representatives, sub-contractors, consultants and third-party providers from and against all losses, claims and damages including legal fees, resulting from:
                                <ol class="sub_list_3">
                                    <li>your violation of any term of these terms of use;</li>
                                    <li>your violation of any third party right, including without limitation any publicity, privacy, or intellectual property right;</li>
                                    <li>your breach of any applicable laws;</li>
                                    <li>any unauthorised, improper, illegal or wrongful use of your account by any person, including a third party, whether or not authorised or permitted by you; and</li>
                                    <li>your breach of any representation, warranty, covenant or undertaking under these terms of use or under applicable law. this indemnification obligation will survive the expiry or termination of these terms of use and your use of the service.</li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>Third Party Websites
                        <ol class="sub_list_2">
                            <li>This Service may contain links to other websites owned and operated by third parties who are not related to the Company ("Third-Party Websites"). Third-Party Websites are not under the control of the Company and the Company shall not be responsible for the content of any Third-Party Websites or any hyperlink contained in a Third-Party Websites and makes no representation or warranty with respect to the content of any such Third-Party Websites.</li>
                            <li>Your access and usage of any Third-Party Websites is entirely at Your own risk. The Company shall not be a party to any transaction between You and a Third-Party Website. Your use of a Third-Party Website is subject to the terms and conditions of that Third-Party Website in addition to these Terms of Use. If there is any inconsistency these Terms of Use prevail.</li>
                            <li>The Service may contain third party advertisements, promotions, etc. (that may or may not contain embedded hyperlinks or referral buttons to Third-Party Websites). The display of such advertising does not in any way imply an endorsement or recommendation by the Company of the relevant advertiser, its products or services or any such Third-Party Website. You must refer directly to the relevant advertiser for all information regarding the advertiser and its products and/or services. The Company accepts no responsibility for any interaction between You and the relevant third party and is released from any liability arising out of or in any way connected with such interaction and/or any defects, deficiencies, claims, etc. arising out of an advertiser's products and/or services.</li>
                        </ol>
                    </li>
                    <li>Registration and Creation of profile 
                        <ol class="sub_list_2">
                            <li>Account Creation and Deletion
                                <ol class="sub_list_3">
                                    <li>In order to use Our Website/App and avail Our Services, You must sign up and create a Profile, which would include Your Personal Information. You may delete Your Profile at any time, for any reason, by following the instructions provided on the Website/App. However, You must note that We reserve the right to retain Your Account Information and other information for the purposes provided under IFTV's Privacy Policy.
                                        <ol class="sub_list_4">
                                            <li>all of the Account Information You submit to Us is true, accurate and complete in all respects;</li>
                                            <li>You will maintain the accuracy of the Account Information that You provide Us with at all times; and</li>
                                            <li>You will update any and all changes in the Account Information by intimating us as per the Terms and IFTV's Privacy Policy.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                            <li>User Responsibilities
                                <ol class="sub_list_3">
                                    <li>You are responsible for maintaining the confidentiality of Your Login Credentials and are fully responsible for all activities that occur under Your Profile (e.g., once logged in). You agree to immediately notify Us of any unauthorised use, or suspected unauthorised use of Your Profile, or any other breach of security, in relation to Your personal information on the Website. Upon such notification from You, We will reasonably assist You in changing Your password.</li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>Access to the app
                        <ol class="sub_list_2">
                            <li>Certain Restrictions
                                <ol class="sub_list_3">
                                    <li>The rights granted to You in these Terms are subject to the following restrictions: except as otherwise authorised, You shall not license, sell, re-sell, lease, transfer, assign, distribute, exchange, host, or by any other means copy, download, capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, deep-link, transmit or retransmit, make any derivative works of, or otherwise commercially exploit any (i) Content, (ii) Services, or (iii) the information (including Personal Information and Sensitive Personal Information) of Users available on the App; whether in whole or in part;</li>
                                    <li>You shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Website, App and Services, or the personal information of other Users, available on the Website;</li>
                                    <li>You shall not access the App and/or its Services, or the personal information of other Users, available on the App in order to build a similar or competitive website, app, product, or service; and</li>
                                    <li>except as expressly stated herein, no part of the App and/or its Service, or the personal information of other Users, available on the Website, may be copied, reproduced, distributed, republished, indexed, framed, downloaded, linked, displayed, posted or transmitted in any form or by any means. Unless otherwise indicated, any future release, update, or other addition to functionality or content of the Website shall be subject to these Terms. All copyright and other proprietary notices on the Website must be retained on all copies thereof.</li>
                                </ol>
                            </li>
                            <li>Modification, Suspension or Discontinuation
                                <ol class="sub_list_3">
                                    <li>You agree that IFTV has the right to temporarily suspend access to the whole or any part of the Services for any reason whatsoever (including technical/operational reasons) and shall be under no liability to You in such an event. Further, IFTV may, but shall not be obliged to, give You notice of any interruption of access to the Services as is reasonably practicable. IFTV will restore access to the Services as soon as reasonably practicable after temporary suspension.</li>
                                    <li>Notwithstanding anything stated above, We reserve the right, at any time and in its sole discretion, to change, modify, suspend, or discontinue the App (in whole, or in part) or any of its Services (in whole, or in part), in compliance with the applicable legal and regulatory framework. You agree that We will not be liable to You or to any third party for any change, modification, suspension, or discontinuation of the Website or its Services, or any part of the Website or its Services thereof.</li>
                                </ol>
                            </li>
                            <li>No Support or Maintenance
                                <ol class="sub_list_3">
                                    <li>If You have any questions, complaints or claims with respect to the App, Content and/or Services, then such correspondence should be directed to the support. However, You acknowledge and agree that We will have no obligation to provide You with any uninterrupted or immediate support or maintenance in connection with the Website, App and/or Services, except as provided under IFTV's Privacy Policy.</li>
                                </ol>
                            </li>
                            <li>Ownership
                                <ol class="sub_list_3">
                                    <li>Excluding Your Account Information, You acknowledge that the App, the entire Content, Services, and all the intellectual property rights, including copyrights, patents, trademarks, designs, and trade secrets in relation to the above are solely owned by IFTV, IFTV Affiliates and/or IFTV's Licensors (“Lawful Owners”).</li>
                                    <li>Notwithstanding anything stated in the Agreement, the Lawful Owners own and retain all intellectual and proprietary rights to the Content and Services throughout the territory of the world in perpetuity. These Terms do not transfer to You or any third party any rights, title or interests in, or to such, intellectual property rights, except for the limited license that is required to view/use the Website, App, Content and Services per the Agreement.</li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>PROVIDED INFORMATION & ACCEPTABLE USE POLICY
                        <ol class="sub_list_2">
                            <li>Risks
                                <ol class="sub_list_3">
                                    <li>You represent and warrant that the Account Information, or any other information, whether personal or sensitive, provided to Us through an email, support forum on the Website, etc. (“Other Information”) does not violate Our 'Acceptable Use Policy' clause below. You may not represent or imply to any person or entity, in any way whatsoever, that the Account Information or Other Information that You provide Us with is sponsored or endorsed by Us in any manner. Because You alone are responsible for Your Account Information and the Other Information that You provide Us with. You may expose Yourself to liability if, for example, the Account Information or Other Information violates the 'Acceptable Use Policy' clause. You must note that We are not obligated to create a backup copy of Your Account Information or Other Information that You provide Us with; We will not be held liable or responsible for the deletion of the Account Information or any Other Information that You provide Us with.</li>
                                </ol>
                            </li>
                            <li>Acceptable Use Policy
                                <ol class="sub_list_3">
                                    <li>The following Terms, along with the provisions of Clause 2 of the Terms, constitutes our “Acceptable Use Policy”:
                                        <br>
                                        You agree not to use the Website/App its Services to collect, upload, create, transmit, display, or distribute the Account Information or Other Information in any way such:
                                            (i) that it violates any third-party right, including any copyright, trademark, patent, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; or
                                            (ii) that it is in violation of any law, regulation, or obligations or restrictions imposed by any third party; or
                                            (iii) that it is hateful, violent, discriminatory, defamatory, racially or ethnically objectionable, unlawful, obscene, sexually suggestive, or pornographic.
                                    </li>
                                    <li>In addition, You agree not to:
                                        <ol class="sub_list_4">
                                            <li>display, upload, modify, transmit, publish, or distribute to, or through, the Website, App or otherwise, any computer viruses, worms, or any software codes, files or programs, intended to damage, limit or alter a computer system, computer network, or data, and/or gain unauthorised access to a computer or computer network;</li>
                                            <li>manipulate the Website to send unsolicited or unauthorised advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise;</li>
                                            <li>manipulate the Website to harvest, collect, gather, or assemble information or data, personal or sensitive regarding any other users or individuals, including their e-mail addresses, with or without their consent.</li>
                                            <li>interfere with, disrupt, or create an undue burden on servers or networks connected to the Website or the data hosted within the Website, or violate the regulations, policies, restrictions or procedures of such networks;</li>
                                            <li>attempt to gain unauthorised access to a third party's information on the Website (or to other computer systems or networks connected to or used together with the Website), whether through password mining or any other means;</li>
                                            <li>harass or interfere with any other user's use and enjoyment of the App it Services; or</li>
                                            <li>use software or automated agents or scripts to produce multiple accounts on the Website, or to generate automated searches, requests, or queries to (or to strip, scrape, or mine data from) the Website.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                            <li>Enforcement
                                <ol class="sub_list_3">
                                    <li>We reserve the right to review Your Account Information or any other information from time to time, and to investigate and/or take appropriate action against You if you violate the 'Acceptable Use Policy' clause, or any other provision of these Terms, or otherwise create liability for Us or any other person or Entity, in Our sole discretion. Such action may include (i) removing or modifying Your Profile, (ii) terminating Your Profile in accordance with the 'Term and Termination clause', and/or (iii) reporting You to, and cooperating with, law enforcement authorities.</li>
                                    <li>Any and all of Your information can be shared in the above circumstances with competent authorities upon any demand or request by them, or in a good faith belief, that such access, preservation, or disclosure is reasonably necessary to: (a) comply with any applicable law; (b) enforce the Terms; (c) respond to Your Service requests and/or for any customer service; or (d) protect the rights, property or personal safety of IFTV, IFTV Affiliates, other Users and the public.</li>
                                </ol>
                            </li>
                            <li>Feedback
                                <ol class="sub_list_3">
                                    <li>If You provide Us with any feedback or suggestions regarding the Website, Content and/or the Services (“Feedback”), You hereby assign to Us all rights in such Feedback and agree that We shall have the right to use and fully exploit such Feedback and related information in any manner We deem appropriate. We will treat any Feedback You provide to Us as non-confidential and non-proprietary; therefore, kindly do not submit to Us any information or ideas that You consider to be confidential or proprietary.</li>
                                </ol>
                            </li>
                        </ol>
                    <li>INDEMNIFICATION
                        <ol class="sub_list_3">
                            <li>By using the app, services and/or the content in any manner whatsoever, you agree, to the maximum extent permitted by law, to defend and indemnify iftv, iftv affiliates and iftv licensor's from any and all claim(s), demand(s), damages, obligations, losses, liabilities, costs or expenses (including but not limited to, all applicable costs and advocate fees) made against us by any third party that is due to, in relation to, or arising out of:</li>
                                <ol class="sub_list_2">
                                    <li>YOUR USE OF THE WEBSITE, APP OR THE SERVICES,</li>
                                    <li>Your violation of these terms and/or iftv's privacy policy,and</li>
                                    <li>Your violation of applicable laws or regulations. We reserve the right, at your expense, to assume the exclusive defence and control of any matter for which you are required to fully indemnify us, and you agree to cooperate with our defence of these claims. Additionally, you agree not to settle any matter without our prior written consent. we will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it, to the extent permissible by applicable law. This indemnity clause is applicable to violations described in or contemplated in these terms.</li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>Limitation of liability
                        <ol class="sub_list_3">
                            <li> To the maximum extent permitted by law, in no event shall iftv and/or iftv affiliates be liable to you for any direct, indirect, consequential, exemplary, incidental, special or punitive damages, lost profits or lost/stolen data arising from, or relating to, the terms; or your use of, or inability to use, the website, app, services and/or submitted content, even if we have been advised of the possibility of such damages. any access to, and use of, the website, app, services and the content is at your sole discretion and risk, and you will be solely responsible for any damage to you or your property, including your device or computer system, or loss of any data, including account information, resulting therefrom. the foregoing limitation of liability shall be to the fullest extent permitted by law in the extent.</li>
                            <li>Notwithstanding anything stated herein, all exclusions in this limitation of liability clause shall be applicable to the maximum extent permitted by law (e.g., some jurisdictions may not permit exclusion of liability for fraudulent misrepresentation).</li>
                        </ol>
                    </li>
                    <li>General Agreement 
                        <ol class="sub_list_2">
                            <li>Electronic Communication
                                <ol class="sub_list_3">
                                    <li>You (a) consent to receive communications from Us in an electronic form; and (b) agree that all Terms and conditions, agreements, notices, disclosures, and other communications that We provide to You electronically satisfy any legal requirement that such communications would satisfy if it were to be in a hardcopy writing.</li>
                                    <li>You give consent to IFTV and IFTV Affiliates to contact You using Your contact information at any time during Your association with IFTV as per IFTV's Privacy Policy. You further acknowledge and agree that You may be contacted for the above purposes using the contact details provided by You, including via phone calls, emails, text messages, and social media apps such as WhatsApp.</li>
                                </ol>
                            </li>
                            <li>Waiver
                                <ol class="sub_list_3">
                                    <li>Any waiver of Our rights or remedy under these Terms shall only be effective if it is in writing, executed by Our duly authorised representative, and shall be applicable only to the circumstances for which it is given. Our failure to exercise or enforce any right or remedy under these Terms shall not operate as a waiver of such right or remedy, nor shall it prevent any future exercise or enforcement of such right or remedy. No single or partial exercise of any right or remedy shall preclude or restrict the further exercise of any such right, or remedy, or other rights or remedies.</li>
                                </ol>
                            </li>
                            <li>Headings and Interpretation
                                <ol class="sub_list_3">
                                    <li>The section titles in these Terms are for convenience only and have no legal or contractual effect. The words “including” and “includes” means “including without limitation”.</li>
                                </ol>
                            </li>
                            <li>Severability
                                <ol class="sub_list_3">
                                    <li>The provision(s) of these Terms shall be sought to be harmoniously interpreted with each other, as well as applicable laws (including the applicable laws based on the jurisdiction of the User's), and upheld to the fullest extent permissible under applicable laws. Further, the provisions contained in this Agreement shall be enforceable independent of each other, and their validity shall not be affected, if any other provision(s) are held to be invalid. If any provision(s) of these Terms are, for any reason, held to be invalid or unenforceable, the other provisions of these Terms will be unimpaired (to the maximum extent permissible), and the invalid or unenforceable provision(s) will be deemed modified so that they are valid and enforceable to the maximum extent permitted by applicable laws. Further, if any of those provision(s) are void, but would be valid if some part of the provision(s) were deleted, the provision(s) in question shall apply with such modification as may be necessary to make them valid.</li>
                                </ol>
                            </li>
                            <li>Relationship between You and Us
                                <ol class="sub_list_3">
                                    <li>You confirm that You do not have an employment, contractor, agency or partnership relationship with IFTV. IFTV is merely providing You the Services on your request. Further, You are acting on either on Your own or behalf of another person, in the manner stated in the Agreement.</li>
                                </ol>
                            </li>
                            <li>Assignment
                                <ol class="sub_list_3">
                                    <li>These Terms, and Your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by You without Our prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. However, You acknowledge and agree that We reserve the right to freely assign Our rights and obligations under these Terms to whomsoever We please. The Terms and conditions set forth in this Agreement shall be binding upon assignees.</li>
                                </ol>
                            </li>
                            <li>Governing Law and Jurisdiction
                                <ol class="sub_list_3">
                                    <li>These Terms and any dispute or claim arising out of or in connection with their subject matter or formation (including non-contractual disputes or claims) shall be governed by and construed in accordance with the laws prevalent in India. You agree that the courts of Thiruvananthapuram shall have exclusive jurisdiction to settle any dispute, or claim, arising out of, or in relation to, this Agreement.</li>
                                </ol>
                            </li>
                            <li>Contact Information
                                <ol class="sub_list_3">
                                    <li>If You wish to contact Us in writing, or if these Terms require You to give notice to Us in writing, please contact Us at <a href="mailto:suppot@iftv.in">suppot@iftv.in</a></li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li>Entire Agreement and Amendments
                        <ol class="sub_list_2">
                            <li>These Terms expressly supersede and completely replace any and all prior 'Terms of Use' published by IFTV regarding the above subject-matter. IFTV shall not be bound by or liable to You for any pre-existing or contemporaneous written or oral representations or warranties, made by anyone, with respect to the Website, App, Content and Services, including by any IFTV Affiliates.</li>
                        </ol>
                        <ol class="sub_list_2">
                            <li>IFTV reserves the right, at its sole discretion, to modify the Terms from time to time (“Updated Terms of Use”). The Updated Terms of Use shall be effective immediately and shall supersede these Terms of Use. IFTV shall not be under an obligation to notify you of any changes to the Terms of Use. You shall be solely responsible for reviewing the Terms of Use from time to time for any modifications. By continuing to use the Website, App, Content and/or Services after the Updated Terms of Use have been published, You affirm Your agreement to the Updated Terms of Use.</li>
                        </ol>
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div class="quick_jump_button_container">
        <div onclick="window.location.href='contents_iftv.php';" class="quick_jump_button">
            Services
        </div>
    </div>
</div>

<?php
require_once 'footer.inc.php';
?>